package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.BancoDePalavras;
import model.Jogador;

public class TelaJogo extends javax.swing.JFrame {

    Inicio telaInicio;
    private Jogador jogador;
    BancoDePalavras bancoDePalavras = new BancoDePalavras();
    String palavraSorteada;
    char[] palavraComTracinhos;
    int quantidadeErros = 0;
    ArrayList<String> palavraSemEspaco;
    String letrasAtuais = "";

    public TelaJogo() {
        initComponents();
        fazerEnforcadoDesaparecer();
    }

    public void voltarTelaInicial() {
        telaInicio = new Inicio();
        telaInicio.setVisible(true);
        dispose();
    }

    public void definirNomeJogador(String nome) {
        if (nome.trim().equals("")) {
            nome = "SEM NOME";
        }
        jogador = new Jogador(nome);
        txtNomeJogador.setText(jogador.getNome());
    }

    public void definirTema(String temaEscolhido) {
        palavraSorteada = bancoDePalavras.sortearPalavra(temaEscolhido);
        palavraComTracinhos = new char[palavraSorteada.length()];
        palavraSemEspaco = new ArrayList<>();
        preencherPalavraSemEspaco(palavraSorteada);

        for (int i = 0; i < palavraSorteada.length(); i++) {
            if (palavraSorteada.charAt(i) != ' ') {
                palavraComTracinhos[i] = '_';
            } else {
                palavraComTracinhos[i] = ' ';
            }
        }

        txtTema.setText(temaEscolhido);
        lblPalavra.setText(exibirTracinhos(palavraComTracinhos));
    }

    public void preencherPalavraSemEspaco(String palavraSorteada) {
        for (int i = 0; i < palavraSorteada.length(); i++) {
            if (palavraSorteada.charAt(i) != ' ') {
                palavraSemEspaco.add(palavraSorteada.charAt(i) + "");
            }
        }
    }

    public String exibirTracinhos(char[] palavraComTracinhos) {
        String tracinhos = "";
        for (int i = 0; i < palavraComTracinhos.length; i++) {
            tracinhos += palavraComTracinhos[i] + " ";
        }
        return tracinhos;
    }

    public void atualizarPalavra(char letra) {
        for (int i = 0; i < palavraSorteada.length(); i++) {
            if (palavraSorteada.charAt(i) == letra) {
                palavraComTracinhos[i] = letra;
            }
        }
    }

    public boolean verificarVitoria() {
        int contador = 0;
        for (int i = 0; i < palavraComTracinhos.length; i++) {
            if (palavraComTracinhos[i] != '_' && palavraComTracinhos[i] != ' ') {
                contador++;
            }
        }
        return contador == palavraSemEspaco.size();
    }

    public void verificarQuantidadeErros(String letra) {
        if (!palavraSorteada.contains(letra)) {
            quantidadeErros++;
            exibirEnforcado(quantidadeErros);
        }
    }

    public void exibirEnforcado(int quantidadeErros) {
        switch (quantidadeErros) {
            case 1:
                enforcado1.setVisible(true);
                break;
            case 2:
                enforcado2.setVisible(true);
                break;
            case 3:
                enforcado3.setVisible(true);
                break;
            case 4:
                enforcado4.setVisible(true);
                break;
            case 5:
                enforcado5.setVisible(true);
                break;
            case 6:
                enforcado6.setVisible(true);
                JOptionPane.showMessageDialog(null, "VOCÊ PERDEU!", "PERDEU", JOptionPane.INFORMATION_MESSAGE);
                voltarTelaInicial();
                break;
        }
    }

    private void jogar(String letra) {
        letrasAtuais += letra;

        lblPalavra.setText(exibirTracinhos(palavraComTracinhos));
        if (verificarVitoria()) {
            JOptionPane.showMessageDialog(null, "PARABÉNS " + jogador.getNome() + ", VOCÊ GANHOU!", "GANHOU!", JOptionPane.INFORMATION_MESSAGE);
            voltarTelaInicial();
        } else {
            verificarQuantidadeErros(letra);
        }
    }

    public void fazerEnforcadoDesaparecer() {
        enforcado1.setVisible(false);
        enforcado2.setVisible(false);
        enforcado3.setVisible(false);
        enforcado4.setVisible(false);
        enforcado5.setVisible(false);
        enforcado6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTema = new javax.swing.JLabel();
        lblTema = new javax.swing.JLabel();
        btnZ = new javax.swing.JButton();
        btnY = new javax.swing.JButton();
        btnX = new javax.swing.JButton();
        btnW = new javax.swing.JButton();
        btnV = new javax.swing.JButton();
        btnU = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        btnS = new javax.swing.JButton();
        btnR = new javax.swing.JButton();
        btnQ = new javax.swing.JButton();
        btnP = new javax.swing.JButton();
        btnO = new javax.swing.JButton();
        btnN = new javax.swing.JButton();
        btnM = new javax.swing.JButton();
        btnL = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        btnJ = new javax.swing.JButton();
        btnI = new javax.swing.JButton();
        btnH = new javax.swing.JButton();
        btnG = new javax.swing.JButton();
        btnF = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnA = new javax.swing.JButton();
        lblPalavra = new javax.swing.JLabel();
        txtNomeJogador = new javax.swing.JLabel();
        lblJogador = new javax.swing.JLabel();
        enforcado6 = new javax.swing.JLabel();
        enforcado5 = new javax.swing.JLabel();
        enforcado4 = new javax.swing.JLabel();
        enforcado3 = new javax.swing.JLabel();
        enforcado2 = new javax.swing.JLabel();
        enforcado1 = new javax.swing.JLabel();
        enforcado0 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da Forca");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTema.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtTema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTema.setToolTipText("");
        getContentPane().add(txtTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, 20));

        lblTema.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTema.setText("TEMA:");
        getContentPane().add(lblTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        btnZ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraZ.png"))); // NOI18N
        btnZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZActionPerformed(evt);
            }
        });
        getContentPane().add(btnZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 30, 30));

        btnY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraY.png"))); // NOI18N
        btnY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYActionPerformed(evt);
            }
        });
        getContentPane().add(btnY, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, 30, 30));

        btnX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraX.png"))); // NOI18N
        btnX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXActionPerformed(evt);
            }
        });
        getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 30, 30));

        btnW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraW.png"))); // NOI18N
        btnW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWActionPerformed(evt);
            }
        });
        getContentPane().add(btnW, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 30, 30));

        btnV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraV.png"))); // NOI18N
        btnV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVActionPerformed(evt);
            }
        });
        getContentPane().add(btnV, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 30, 30));

        btnU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraU.png"))); // NOI18N
        btnU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUActionPerformed(evt);
            }
        });
        getContentPane().add(btnU, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 30, 30));

        btnT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraT.png"))); // NOI18N
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });
        getContentPane().add(btnT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 30, 30));

        btnS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraS.png"))); // NOI18N
        btnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSActionPerformed(evt);
            }
        });
        getContentPane().add(btnS, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 30, 30));

        btnR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraR.png"))); // NOI18N
        btnR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRActionPerformed(evt);
            }
        });
        getContentPane().add(btnR, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 30, 30));

        btnQ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraQ.png"))); // NOI18N
        btnQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 30, 30));

        btnP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraP.png"))); // NOI18N
        btnP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPActionPerformed(evt);
            }
        });
        getContentPane().add(btnP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 30, 30));

        btnO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraO.png"))); // NOI18N
        btnO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOActionPerformed(evt);
            }
        });
        getContentPane().add(btnO, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 30, 30));

        btnN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraN.png"))); // NOI18N
        btnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNActionPerformed(evt);
            }
        });
        getContentPane().add(btnN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 30, 30));

        btnM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraM.png"))); // NOI18N
        btnM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMActionPerformed(evt);
            }
        });
        getContentPane().add(btnM, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 30, 30));

        btnL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraL.png"))); // NOI18N
        btnL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLActionPerformed(evt);
            }
        });
        getContentPane().add(btnL, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 30, 30));

        btnK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraK.png"))); // NOI18N
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });
        getContentPane().add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 30));

        btnJ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraJ.png"))); // NOI18N
        btnJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJActionPerformed(evt);
            }
        });
        getContentPane().add(btnJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 30, 30));

        btnI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraI.png"))); // NOI18N
        btnI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIActionPerformed(evt);
            }
        });
        getContentPane().add(btnI, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 30, 30));

        btnH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraH.png"))); // NOI18N
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });
        getContentPane().add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 30, 30));

        btnG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraG.png"))); // NOI18N
        btnG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGActionPerformed(evt);
            }
        });
        getContentPane().add(btnG, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 30, 30));

        btnF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraF.png"))); // NOI18N
        btnF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFActionPerformed(evt);
            }
        });
        getContentPane().add(btnF, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 30, 30));

        btnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraE.png"))); // NOI18N
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });
        getContentPane().add(btnE, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 30, 30));

        btnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraD.png"))); // NOI18N
        btnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDActionPerformed(evt);
            }
        });
        getContentPane().add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 30, 30));

        btnC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraC.png"))); // NOI18N
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        getContentPane().add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 30, 30));

        btnB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraB.png"))); // NOI18N
        btnB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBActionPerformed(evt);
            }
        });
        getContentPane().add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 30, 30));

        btnA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letraA.png"))); // NOI18N
        btnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAActionPerformed(evt);
            }
        });
        getContentPane().add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 30, 30));

        lblPalavra.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPalavra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblPalavra, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 490, 40));

        txtNomeJogador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtNomeJogador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(txtNomeJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 190, 20));

        lblJogador.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblJogador.setText("JOGADOR:");
        getContentPane().add(lblJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 100, 20));

        enforcado6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado6.png"))); // NOI18N
        getContentPane().add(enforcado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        enforcado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado5.png"))); // NOI18N
        getContentPane().add(enforcado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        enforcado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado4.png"))); // NOI18N
        getContentPane().add(enforcado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        enforcado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado3.png"))); // NOI18N
        getContentPane().add(enforcado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        enforcado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado2.png"))); // NOI18N
        getContentPane().add(enforcado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        enforcado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado1.png"))); // NOI18N
        getContentPane().add(enforcado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        enforcado0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enforcado0.png"))); // NOI18N
        getContentPane().add(enforcado0, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg_Jogo.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAActionPerformed
        btnA.setVisible(false);
        atualizarPalavra('A');
        jogar("A");
    }//GEN-LAST:event_btnAActionPerformed

    private void btnBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBActionPerformed
        btnB.setVisible(false);
        atualizarPalavra('B');
        jogar("B");
    }//GEN-LAST:event_btnBActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        btnC.setVisible(false);
        atualizarPalavra('C');
        jogar("C");
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        btnD.setVisible(false);
        atualizarPalavra('D');
        jogar("D");
    }//GEN-LAST:event_btnDActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        btnE.setVisible(false);
        atualizarPalavra('E');
        jogar("E");
    }//GEN-LAST:event_btnEActionPerformed

    private void btnFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFActionPerformed
        btnF.setVisible(false);
        atualizarPalavra('F');
        jogar("F");
    }//GEN-LAST:event_btnFActionPerformed

    private void btnGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGActionPerformed
        btnG.setVisible(false);
        atualizarPalavra('G');
        jogar("G");
    }//GEN-LAST:event_btnGActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
        btnH.setVisible(false);
        atualizarPalavra('H');
        jogar("H");
    }//GEN-LAST:event_btnHActionPerformed

    private void btnIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIActionPerformed
        btnI.setVisible(false);
        atualizarPalavra('I');
        jogar("I");
    }//GEN-LAST:event_btnIActionPerformed

    private void btnJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJActionPerformed
        btnJ.setVisible(false);
        atualizarPalavra('J');
        jogar("J");
    }//GEN-LAST:event_btnJActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        btnK.setVisible(false);
        atualizarPalavra('K');
        jogar("K");
    }//GEN-LAST:event_btnKActionPerformed

    private void btnLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLActionPerformed
        btnL.setVisible(false);
        atualizarPalavra('L');
        jogar("L");
    }//GEN-LAST:event_btnLActionPerformed

    private void btnMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMActionPerformed
        btnM.setVisible(false);
        atualizarPalavra('M');
        jogar("M");
    }//GEN-LAST:event_btnMActionPerformed

    private void btnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNActionPerformed
        btnN.setVisible(false);
        atualizarPalavra('N');
        jogar("N");
    }//GEN-LAST:event_btnNActionPerformed

    private void btnOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOActionPerformed
        btnO.setVisible(false);
        atualizarPalavra('O');
        jogar("O");
    }//GEN-LAST:event_btnOActionPerformed

    private void btnPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPActionPerformed
        btnP.setVisible(false);
        atualizarPalavra('P');
        jogar("P");
    }//GEN-LAST:event_btnPActionPerformed

    private void btnQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQActionPerformed
        btnQ.setVisible(false);
        atualizarPalavra('Q');
        jogar("Q");
    }//GEN-LAST:event_btnQActionPerformed

    private void btnRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRActionPerformed
        btnR.setVisible(false);
        atualizarPalavra('R');
        jogar("R");
    }//GEN-LAST:event_btnRActionPerformed

    private void btnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSActionPerformed
        btnS.setVisible(false);
        atualizarPalavra('S');
        jogar("S");
    }//GEN-LAST:event_btnSActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        btnT.setVisible(false);
        atualizarPalavra('T');
        jogar("T");
    }//GEN-LAST:event_btnTActionPerformed

    private void btnUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUActionPerformed
        btnU.setVisible(false);
        atualizarPalavra('U');
        jogar("U");
    }//GEN-LAST:event_btnUActionPerformed

    private void btnVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVActionPerformed
        btnV.setVisible(false);
        atualizarPalavra('V');
        jogar("V");
    }//GEN-LAST:event_btnVActionPerformed

    private void btnWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWActionPerformed
        btnW.setVisible(false);
        atualizarPalavra('W');
        jogar("W");
    }//GEN-LAST:event_btnWActionPerformed

    private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
        btnX.setVisible(false);
        atualizarPalavra('X');
        jogar("X");
    }//GEN-LAST:event_btnXActionPerformed

    private void btnYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYActionPerformed
        btnY.setVisible(false);
        atualizarPalavra('Y');
        jogar("Y");
    }//GEN-LAST:event_btnYActionPerformed

    private void btnZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZActionPerformed
        btnZ.setVisible(false);
        atualizarPalavra('Z');
        jogar("Z");
    }//GEN-LAST:event_btnZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnF;
    private javax.swing.JButton btnG;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnI;
    private javax.swing.JButton btnJ;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnL;
    private javax.swing.JButton btnM;
    private javax.swing.JButton btnN;
    private javax.swing.JButton btnO;
    private javax.swing.JButton btnP;
    private javax.swing.JButton btnQ;
    private javax.swing.JButton btnR;
    private javax.swing.JButton btnS;
    private javax.swing.JButton btnT;
    private javax.swing.JButton btnU;
    private javax.swing.JButton btnV;
    private javax.swing.JButton btnW;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnY;
    private javax.swing.JButton btnZ;
    private javax.swing.JLabel enforcado0;
    private javax.swing.JLabel enforcado1;
    private javax.swing.JLabel enforcado2;
    private javax.swing.JLabel enforcado3;
    private javax.swing.JLabel enforcado4;
    private javax.swing.JLabel enforcado5;
    private javax.swing.JLabel enforcado6;
    private javax.swing.JLabel lblJogador;
    private javax.swing.JLabel lblPalavra;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel txtNomeJogador;
    private javax.swing.JLabel txtTema;
    // End of variables declaration//GEN-END:variables
}
